name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: npm install
        run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: npm lint
        uses: actions/npm@master
        with:
         args: run lint
      - name: Build 
        run: |
          npm install
          npm run-script build
      - name: Push
        run: |
          git push -f git@github.com:sidorof/d3-chart-formats.git master:gh-pages,
          echo "complete?".
