name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: npm run build
    - name: Run a multi-line script
      run: |
        git push -f git@github.com:sidorof/d3-chart-formats.git master:gh-pages,
        echo "complete?".
